### ISSUE TITLE
New Domains to add at the script

### ISSUE THREAD

**Issue by denisfi** [yongzhenlow/email-autocomplete#22] opened 2020-12-21 14:32 UTC
Hi Yong, my name is Denis, from Brazil, and i'd like to add at the script some important domains that can improve the form complete with the most used domain from the world., AND i'd like to know why the first caso don't work. I need to add a blank information at first array to work fine! They are:

'','gmail.com','hotmail.com','hotmail.com.br','outlook.com','outlook.com.br','yahoo.com','yahoo.com.br','aol.com','bol.com.br','brazilmail.com.br','brfree.com.br','brturbo.com.br','colombo.com.br','dglnet.com.br','facebook.com','globalsite.com.br','globo.com','globomail.com','gmx.at','gmx.ch','gmx.com','gmx.net','ibest.com.br','icloud.com','ig.com.br','itelefonica.com.br','keemail.me','live.com','mac.com','mail.com','mail.ru','mailbr.com.br','me.com','msn.com','oi.com.br','osite.com.br','pop.com.br','posteo.com.br','protonmail.ch','protonmail.com','superig.com.br','terra.com.br','tuta.io','tutamail.com','tutanota.com','tutanota.de','ubbi.com.br','uol.com.br','veloxmail.com.br','windowslive.com','yahoo.co.uk','yahoo.es','yahoo.fr','yahoo.it','yandex.com','yandex.mail','ymail.com','zipmail.com.br','zoho.com','zohomail.com'

Thanks a lot for the script.

Denis Iongbloed

**Comment by yongzhenlow** [comment] 2020-12-21 15:09
Hey there Denis,

So, I used the list of emails you listed, without the empty string into the `domains` option and it seems to be working. Not sure if I understood the problem correctly, let me know?

![Alt Text](https://media.giphy.com/media/0Vqowjxspn2Pn9TB9u/giphy.gif)

**Comment by denisfi** [comment] 2020-12-21 18:39
Hi Yoing, thanks for your response!

When I tried to write the “gmail” (the first string) after the all the new strings domains, the first option wouldn't appears, only worked for me after I inserted the empty string. It was bizarre, but happen for me.

I used Opera browser (last version)

**Comment by yongzhenlow** [comment] 2021-01-17 15:31
@denisfi I'm unable to reproduce the issue on Opera 73.0.3856.344 (Latest version).

I recommend you isolate the issue and if you are able to provide more details on how to reproduce I'll reopen.

Closing this

**Closed by yongzhenlow** 2021-01-17 15:31 UTC
